version: 2
jobs:
  build-python37:
    docker:
      - image: python:3.7-alpine3.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --no-cache make bash
            pip install .[flask] pytest pytest-cov flask
      - run:
          name: run tests
          command: pytest .


workflows:
  version: 2
  build:
    jobs:
      - build-python37
