version: 2
jobs:
  build-python37:
    docker:
      - image: python:3.7-alpine3.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install poetry
            poetry install -v -E flask
      - run:
          name: run tests
          command: pytest .


workflows:
  version: 2
  build:
    jobs:
      - build-python37
