version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.12.7
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: install dependencies
          command: poetry install -v -E flask

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: lint code
          command: poetry run ruff check

      - run:
          name: run tests
          command: |
            poetry run coverage run -m pytest .
            poetry run coveralls

workflows:
  version: 2
  build:
    jobs:
      - build
